const ipsumChunks = [
  'Neither of us want to see you go Hollow.',
  'Entrust thine flesh to me.',
  'Thy Scent is very human, indeed. …But, not intolerable…',
  'According to legend, the knight Artorias crossed the Abyss, and annihilated the atrocious Darkwraiths.',
  'This place is treacherous. Do watch your step, eh?',
  'What are you doing in the Catacombs? Are you a Cleric or something?',
  'May we discuss Miracles, then?',
  'This knight of Catarina expresses his deepest gratitude.',
  'I was so absorbed in thought, I just drifted away.',
  'You see, I\'m actually in a bit of a fix.',
  'I will stay behind, to gaze at the sun.',
  'But cometh thee not for the grave of Sir Artorias?',
  'Traversing the dark? \'Tis but a fairy tale.',
  'To thine kinsmen forever stay true. Dare\'st not in any attempt to double-cross.',
  'Well indeed, thou art a strange one!',
  'What a fool we have, what a wretched fool we have!',
  'I only hope that my impure tongue does not offend.',
  'Finally, the curse of the Undead will be lifted, and I can die human.',
  'Well, hello again. You seem to be doing all right. Need anything forged?',
  'You won\'t make it through the night without employing my services!',
  'It\'s fine to be Undead, but keep a level head, eh? Hah hah hah!',
  'Don\'t get yourself killed. Neither of us want to see you go Hollow.',
  'Mm, you seem quite lucid! A rare thing in these times.',
  'Oh, do not fret. Life isn\'t all about sorcery. You will find your own way.',
  'All progress demands sacrifice. And I certainly bear no antipathy for that wonderful scaleless beast.',
  'Let me give you a nibble of advice. Don\'t even consider visiting Anor Londo.',
  'I\'ll be there to claim your trinkets. Gazing at your final twisted grimace!',
  'Go along, try and make something of yourself. But nothing will come of it.',
  'Fine then, rush in like a naked babe, and be skinned alive!',
  'Oh, your face! You\'re practically Hollow.',
  'No problem. Have a seat and get comfortable. We\'ll both be Hollow before you know it.',
  'He left for Blighttown, but never came back.',
  'I hope he enjoys his new life as a Hollow.',
  'The virtuous lass came back alone, and in absolute tatters…',
  'I may be crestfallen, but I\'m not defenseless, you rascal!',
  'Halt! This is the tomb of the Great Lord Gwyn.',
  'Very well, Blade of the Darkmoon. Please state thy wish.',
  'Thou shalt not go unpunished!',
  'O Heretic, swathed in Dark… An eternal curse upon thee…',
  'Undead Warrior, conqueror of the Four Kings, is this not your wish?',
  'After the advent of fire, the ancient lords found the three souls.',
  'And soon, the flames did fade, and only Dark remained.',
  'Undead warrior, we stand at the crossroad. Only I know the truth about your fate.',
  'Entrust thine flesh to me.',
  'They were strong, but saw not the truth.',
  'rom my home I was taken, and banish\'d to a plane of distortion.',
  
]